Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**'
    - 'spec/ifql/**'
Metrics/MethodLength:
  Max: 100
Metrics/ClassLength:
  Max: 1500
Metrics/BlockLength:
  Max: 200
Metrics/PerceivedComplexity:
  Max: 13
Metrics/CyclomaticComplexity:
  Max: 11
Metrics/AbcSize:
  Exclude:
    - 'spec/**'
    - 'spec/ifql/**'
    - 'lib/telemetry/ifql/parser.rb'
Naming/MethodParameterName:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
Style/FrozenStringLiteralComment:
  Enabled: false